title: Animesh Kumar
email: animeshk452@gmail.com
description: MS Computer Science | AI/ML Specialist | Arizona State University
baseurl: ""
url: "https://animeshkumar.github.io"

# Social links
github_username: Animesh452
linkedin_username: your-linkedin

# Theme settings
theme: minima
