title: Animesh Kumar
subtitle: MS Computer Science | AI/ML Specialist | Arizona State University
description: Passionate about machine learning, computer vision, and distributed systems
author: Animesh Kumar
email: animeshk452@gmail.com

# Social network links
social-network-links:
  github: your-github-username
  linkedin: your-linkedin-username
  email: animeshk452@gmail.com

# Theme
remote_theme: daattali/beautiful-jekyll

# Navigation
navbar-links:
  About Me: "aboutme"
  Projects: "projects"
  Publications: "publications"
  Contact: "contact"

# Avatar - add your photo URL here
avatar: "file:///C:/Users/Win11/AppData/Local/Packages/5319275A.WhatsAppDesktop_cv1g1gvanyjgm/TempState/2FEC3A0CBF3856FBCD22A3BAFC9EE8DB/WhatsApp%20Image%202025-09-23%20at%2023.26.05_77b2d556.jpg"

# Footer
footer-links-active:
  github: true
  linkedin: true
  email: true
